@url = http://127.0.0.1:8080
@endpoint = /api/todolist

### GET all TODO items
GET {{url}}{{endpoint}} HTTP/1.1

### POST add new TODO item

# @name create
POST {{url}}{{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "description":"testing",
    "owner":"rest client"
}

### UPDATE a TODO item
PUT {{url}}{{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "id":"{{create.response.body.*}}",
    "description":"testing updated"
}

### DELETE a TODO item
DELETE {{url}}{{endpoint}}/{{create.response.body.*}} HTTP/1.1
